# Generated by Django 2.1.2 on 2018-10-15 17:06

from django.db import migrations, models
import infohub.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('slug', models.SlugField(max_length=4096, unique=True, verbose_name='Slug')),
                ('name', infohub.fields.SingleLineTextField(unique=True, verbose_name='Name')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
