# Generated by Django 2.1.2 on 2018-10-17 13:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import infohub.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('hash', models.SlugField(max_length=128, unique=True, verbose_name='Hash')),
                ('url', models.URLField(max_length=2096, verbose_name='URL')),
                ('title', infohub.fields.SingleLineTextField(blank=True, null=True, verbose_name='Title')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Metadata')),
                ('text', models.TextField(verbose_name='Text')),
                ('state', django_fsm.FSMField(default='new', max_length=50, protected=True, verbose_name='State')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content type')),
                ('related', models.ManyToManyField(related_name='_document_related_+', to='documents.Document', verbose_name='Related documents')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
